require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorPreferences', :path => '../../node_modules/@capacitor/preferences'
  pod 'CapacitorShare', :path => '../../node_modules/@capacitor/share'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Suppress CapacitorCordova double-quoted include warnings
      config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
      # Prevent "Update to recommended settings" warning
      config.build_settings['ENABLE_STRICT_OBJC_MSGSEND'] = 'YES'
      config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
      config.build_settings['CLANG_ANALYZER_NONNULL'] = 'YES'
      config.build_settings['CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION'] = 'YES_AGGRESSIVE'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING'] = 'YES'
      config.build_settings['CLANG_WARN_BOOL_CONVERSION'] = 'YES'
      config.build_settings['CLANG_WARN_COMMA'] = 'YES'
      config.build_settings['CLANG_WARN_CONSTANT_CONVERSION'] = 'YES'
      config.build_settings['CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS'] = 'YES'
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'YES'
      config.build_settings['CLANG_WARN_EMPTY_BODY'] = 'YES'
      config.build_settings['CLANG_WARN_ENUM_CONVERSION'] = 'YES'
      config.build_settings['CLANG_WARN_INFINITE_RECURSION'] = 'YES'
      config.build_settings['CLANG_WARN_INT_CONVERSION'] = 'YES'
      config.build_settings['CLANG_WARN_NON_LITERAL_NULL_CONVERSION'] = 'YES'
      config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'YES'
      config.build_settings['CLANG_WARN_OBJC_LITERAL_CONVERSION'] = 'YES'
      config.build_settings['CLANG_WARN_RANGE_LOOP_ANALYSIS'] = 'YES'
      config.build_settings['CLANG_WARN_STRICT_PROTOTYPES'] = 'YES'
      config.build_settings['CLANG_WARN_SUSPICIOUS_MOVE'] = 'YES'
      config.build_settings['CLANG_WARN_UNGUARDED_AVAILABILITY'] = 'YES_AGGRESSIVE'
      config.build_settings['CLANG_WARN_UNREACHABLE_CODE'] = 'YES'
      config.build_settings['GCC_WARN_64_TO_32_BIT_CONVERSION'] = 'YES'
      config.build_settings['GCC_WARN_ABOUT_RETURN_TYPE'] = 'YES_ERROR'
      config.build_settings['GCC_WARN_UNDECLARED_SELECTOR'] = 'YES'
      config.build_settings['GCC_WARN_UNUSED_FUNCTION'] = 'YES'
      config.build_settings['COPY_PHASE_STRIP'] = 'NO'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
      config.build_settings['ENABLE_NS_ASSERTIONS'] = 'NO'
      config.build_settings['ENABLE_TESTABILITY'] = 'YES'
      config.build_settings['MTL_ENABLE_DEBUG_INFO'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['SDKROOT'] = 'iphoneos'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      # Disable user script sandboxing for CocoaPods scripts
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end

  # Also disable sandboxing on the main App target
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |config_name, config_file|
      config_file.attributes['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
